### ISSUE TITLE
JetStream Data at rest encryption

### ISSUE THREAD

**Issue by ripienaar** [nats-io/nats-architecture-and-design#15]
## Overview

We need to document the data at rest encryption system.

We have a Google document (internal) that describes the overall design, this should be turned into a ADR and docs.nats.io documentation should be made

The Server PR is https://github.com/nats-io/nats-server/pull/2302 this is now based on chachapoly and not AES as documented.

## Tasks

- [x] Outline documentation approved
- [x] Create an ADR if applicable 
- [x] docs.nats.io updated https://docs.nats.io/jetstream/encryption_at_rest
- [x] Supporting blog posts or videos for marketing
